anymail/django-anymail

- anymail/backends/sendgrid.py
- tests/test_sendgrid_backend.py
The `to` field is required even if providing recipient addresses in x-smtpapi. See https://sendgrid.com/docs/API_Reference/Web_API/mail.html#-send.
> Set to field when using merge_data

- tests/test_mailgun_backend.py
- tests/test_mandrill_backend.py
- tests/test_postmark_backend.py
- tests/test_sendgrid_backend.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- .travis.yml
- README.rst
- anymail/backends/sparkpost.py
- anymail/urls.py
- anymail/webhooks/sparkpost.py
- docs/esps/index.rst
- docs/esps/sparkpost.rst
- docs/installation.rst
- setup.py
- tests/test_sparkpost_backend.py
- tests/test_sparkpost_integration.py
- tests/test_sparkpost_webhooks.py
Work in progress. To do:
Closes #11 (once complete)
> Add SparkPost support

- anymail/backends/base.py
- anymail/utils.py
- tests/test_general_backend.py
- tests/test_utils.py
In BasePayload, ensure any Django ugettext_lazy
(or similar) are converted to real strings before
handing off to ESP code. This resolves problems where
calling code expects it can use lazy strings "anywhere",
but non-Django code (requests, ESP packages) don't
always handle them correctly.
* Add utils helpers for lazy objects (is_lazy, force_non_lazy*)
* Add lazy object handling to utils.Attachment
* Add lazy object handling converters to BasePayload attr
processing where appropriate. (This ends up varying by
the expected attribute type.)
Fixes #34.
> Handle Django lazy strings.

- anymail/backends/sendgrid.py
- anymail/backends/sendgrid_v2.py
- anymail/utils.py
- docs/esps/sendgrid.rst
- tests/mock_requests_backend.py
- tests/test_general_backend.py
- tests/test_sendgrid_backend.py
- tests/test_sendgrid_integration.py
- tests/test_sendgrid_v2_backend.py
- tests/test_sendgrid_v2_integration.py
- tests/test_utils.py
**SendGrid:** **[possibly-breaking]** Update SendGrid backend to newer Web API v3. This should be a transparent change for most projects. Exceptions: if you use SendGrid username/password auth, esp_extra with "x-smtpapi", or multiple Reply-To addresses, please review the [porting notes](http://anymail.readthedocs.io/en/latest/esps/sendgrid/#sendgrid-v3-upgrade).
Closes #28
> SendGrid: update to v3 send API

- anymail/utils.py
- tests/test_mailgun_backend.py
- tests/utils.py
The comment in `MIMEBase.get_payload()` explains that it can return `None` when it is a multi-part message. In this case we need to convert the whole thing to bytes.
Without this patch, in production you get a crasher like the following:
File "/home/luke/.virtualenvs/cciw/lib/python3.5/site-packages/django/core/mail/message.py", line 342, in send
return self.get_connection(fail_silently).send_messages([self])
File "/home/luke/.virtualenvs/cciw/lib/python3.5/site-packages/anymail/backends/base.py", line 88, in send_messages
sent = self._send(message)
File "/home/luke/.virtualenvs/cciw/lib/python3.5/site-packages/anymail/backends/base_requests.py", line 56, in _send
return super(AnymailRequestsBackend, self)._send(message)
File "/home/luke/.virtualenvs/cciw/lib/python3.5/site-packages/anymai …
> Fixed crasher when sending rfc822 messages as attachments.

- AUTHORS.txt
- anymail/backends/mailjet.py
- anymail/exceptions.py
- tests/mock_requests_backend.py
- tests/test_mailjet_backend.py
- tests/test_mailjet_integration.py
This PR is based on #53, but rebases on the latest master (0.10) and adds two fixes on top of it (fix for older Mock versions and a fix for test + update for changes in 0.10).
Same caveat holds, the end-to-end tests with Mailjet server is still missing and the documentation is not updated, but I don't have time to address that at the moment.
Closes #53, #65.
> Mailjet backend support (for v0.10)

- anymail/urls.py
- anymail/webhooks/base.py
- anymail/webhooks/mandrill.py
- docs/esps/mandrill.rst
- tests/test_mandrill_webhooks.py
* Added MandrillAutomaticWebhookView which updates signals and returns esp_to_anymail_event for the proper view based on the esp_type
* Three test cases which verifies the correct esp_to_anymail_event is called for hard_bounce and inbound
> Add automatic routing for Mandrill. Closes #86

- anymail/backends/console.py
- anymail/backends/test.py
- tests/test_send_signals.py
Two commits to assist use in development: modify the test backend to use unique message ID's rather than a hardcoded `1`.  Also, add a console backend which provides anymail statuses and signal handling, while printing sent messages to the console.
Re Issue #85.
> Un-hardcode message ID in test backend, and add console backend

- AUTHORS.txt
- anymail/backends/sendinblue.py
- docs/esps/index.rst
- docs/esps/sendinblue.rst
- tests/test_sendinblue_backend.py
- tests/test_sendinblue_integration.py
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Feature
| Tickets (_issues_) concerned               | fixed #84
---
I've begin an integration of `SendinBlue` with the new API v3, i took the choice to directly call the API and to not use the official python client implementation as recommended by `django-anymail` documentation.
Please feel free to review my code, contribute or just help me with some tips or good idea.
I will continue this work soon 👍 
-  [x] Link the issue to this PR
-  [x] Add my name in `AUTHORS.txt`
-  [x] Create the Backend and Payload classes
-  [x] Add or modify the attached tests
-  [x] Add or modify the attached …
> [WIP] Feature integration sendinblue

- anymail/urls.py
- anymail/webhooks/sendinblue.py
- docs/esps/index.rst
- docs/esps/sendinblue.rst
- tests/test_sendinblue_webhooks.py
> [WIP] SendinBlue: implement tracking webhooks

- README.rst
- anymail/backends/amazon_ses.py
- anymail/urls.py
- anymail/utils.py
- anymail/webhooks/amazon_ses.py
- docs/contributing.rst
- docs/esps/amazon_ses.rst
- docs/esps/index.rst
- docs/sending/django_email.rst
- setup.py
- tests/test_amazon_ses_backend.py
- tests/test_amazon_ses_inbound.py
- tests/test_amazon_ses_integration.py
- tests/test_amazon_ses_webhooks.py
- tox.ini
In-progress implementation of Amazon SES support (#54). This first commit implements all backend functionality other than templates.
For testing, pip can install directly from this feature branch:
```bash
pip install https://github.com/anymail/django-anymail/tarball/feature_amazon_ses#egg=django-anymail[amazon_ses]
```
(You may need to add `--upgrade` if you already have Anymail installed. The `#egg=django-anymail[amazon_ses]` part lets pip know to also install the extra dependencies for amazon_ses support in django-anymail—namely, boto3.)
To use the backend, specify `EMAIL_BACKEND = "anymail.backends.amazon_ses.EmailBackend"` in your Django settings. There are no specific Anymail settings required—[boto3 finds your AWS credentials](http://boto3.readthedocs.io/en/stable/guide/configuration …
> [WIP] Amazon SES integration

- anymail/backends/sendgrid.py
- anymail/backends/sendgrid_v2.py
- anymail/webhooks/sendgrid.py
- tests/test_sendgrid_backend.py
- tests/test_sendgrid_v2_backend.py
- tests/test_sendgrid_webhooks.py
- tests/utils.py
Based our discussion in #108.
According to SendGrid support, the `Message-ID` and `smtp-id` are both used by SendGrid to set their unique message ID. Based on the conversation with SendGrid support we should use a custom arg with a key named something other than `Message-ID` or `smtp-id`. 
Tried to set this up to ensure backwards compatibility for users who upgrade so that the `smtp-id` still gets referenced if the `anymail-id` is not present in the webhook data.
> Modified custom_arg message_id for compatibility with SendGrid webhook

- CHANGELOG.rst
- anymail/utils.py
- docs/sending/django_email.rst
- tests/test_utils.py
As explained in #125, this should bring `django-anymail` more inline with the behavior of many MUAs that optimistically consider an attachment as "inline" when it has a `Content-ID` but no `Content-Disposition`.
> also consider Content-ID when marking attachment as inline

- anymail/backends/base.py
- anymail/backends/sendgrid.py
- tests/test_sendgrid_backend.py
SendGrid supports specifying the metadata per message when using the bulk-sending API, like with merge data. This is really useful in some cases, so here's simple support for it using the same kind of API as merge data.
> Support for per-message meta data for SendGrid

- CHANGELOG.rst
- anymail/backends/base.py
- anymail/backends/mailgun.py
- anymail/backends/mailjet.py
- anymail/backends/mandrill.py
- anymail/backends/postmark.py
- anymail/backends/sparkpost.py
- anymail/backends/test.py
- anymail/message.py
- docs/esps/amazon_ses.rst
- docs/esps/index.rst
- docs/esps/mailgun.rst
- docs/esps/mailjet.rst
- docs/esps/sendinblue.rst
- docs/sending/anymail_additions.rst
- docs/sending/templates.rst
- tests/test_general_backend.py
- tests/test_mailgun_backend.py
- tests/test_mailjet_backend.py
- tests/test_mandrill_backend.py
- tests/test_postmark_backend.py
- tests/test_sparkpost_backend.py
(Cannot be supported for Amazon SES or SendinBlue. See #141.)
> Add merge_metadata

- anymail/backends/mailgun.py
- docs/esps/mailgun.rst
- tests/test_mailgun_backend.py
> Add template support for Mailgun

- anymail/backends/sendinblue.py
- docs/esps/index.rst
- docs/esps/sendinblue.rst
- tests/test_sendinblue_backend.py
- Multiple tags can be send now (regardless of template or not)
- When sending a mail using a template, display name is supported on 'to', 'bcc', 'cc' and 'replyTo'. Also supports overriding 'from_email' and 'subject'
- Removed use of deprecated SendinBlue API endpoint
> Improvements to Sendinblue Backend

- CHANGELOG.rst
- anymail/backends/mailgun.py
- docs/esps/index.rst
- docs/esps/mailgun.rst
- tests/test_mailgun_backend.py
- tests/test_mailgun_integration.py
Mailgun has two different template mechanisms and two different ways
of providing substitution variables to them. Update Anymail's
normalized merge_data handling to work with either (while preserving
existing batch send and metadata capabilities that also use Mailgun's
custom data and recipient variables parameters).
Completes work started by @anstosa in #156.
Closes #155.
> Mailgun: make merge_data work with stored handlebars templates

- .travis.yml
- CHANGELOG.rst
- anymail/backends/mailgun.py
- tests/mock_requests_backend.py
- tests/test_mailgun_backend.py
- tox.ini
urllib3 v1.25 fixes non-ASCII filenames in multipart form data to be
RFC 5758 compliant by default, so our earlier workaround is no longer
needed. Disable the workaround if we detect that Requests is using a
fixed version of urllib3.
Closes #157
> Mailgun: disable RFC 5758 filename workaround when urllib3 is fixed

- docs/sending/tracking.rst
noticed a minor typo while scanning your email status tracking docs; made a few other minor text edits while I was there.
> fix typos + minor text edits

- tests/test_mailgun_integration.py
In the live integration tests, work around Mailgun's recent change
to how inline attachments are reported in "accepted" events data.
(But keep it working either way, since it seems likely this change was
unintentional—other event types still exclude inline attachments from
`event.message.attachments`.)
Fixes #172
> Tests: work around Mailgun event reporting change

- docs/esps/sendgrid.rst
Document SendGrid's unpredictable behavior around forcing `charset="iso-8859-1"` into text attachments. (Since it seems to be happening again.)
See #150 for details.
> SendGrid: document text attachment charset bug

- anymail/apps.py
- anymail/checks.py
- docs/help.rst
- docs/installation.rst
- tests/test_checks.py
(And add a system check to warn about its use in production deployment.)
(See this [comment](https://github.com/anymail/django-anymail/issues/144#issuecomment-565001324) from @jonathan-s suggesting it be documented.)
> Docs: document DEBUG_API_REQUESTS setting

- docs/esps/sendinblue.rst
Attachments now work with templates as long as you are using the new
template language.
I just tried it with `message.attach_file("/path/to/file.ext")` using a template and it works like a charm. This is very fortunate.
See also: https://developers.sendinblue.com/changelog/send-attachment-with-template-through-apiv3
Thanks for this awesome library!
> SendinBlue: Attachments now work with templates

- CHANGELOG.rst
- anymail/backends/sendgrid.py
- tests/test_sendgrid_backend.py
In SendGrid backend, support non-batch template send to multiple
recipients when `merge_global_data` is set without `merge_data`.
Regression introduced in v6.0.
Fixes #179
> SendGrid: Fix multiple recipients with only merge_global_data

- CHANGELOG.rst
- anymail/backends/postmark.py
- tests/test_postmark_backend.py
Hi,
This PR fixes a bug in the Postmark backend.
Attempting to send a templated email with a single recipient fails, as a `TemplateModel` is not being set. This is required for the [/email/withTemplate/](https://postmarkapp.com/developer/api/templates-api#email-with-template) endpoint.
This was causing the send to fail with a `Postmark API response 422 (Unprocessable Entity)`
> Postmark: Send a templated email with a single recipient

- anymail/utils.py
Django3.0 comes with the following deprecation warning:
```
/usr/local/lib/python3.7/site-packages/anymail/utils.py:150: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
```
This PR fixes the warning by using `force_str` when run under Python 3.
> fix Django3.0 deprecation warning: use force_str instead of force_text on Py3

- CHANGELOG.rst
- anymail/webhooks/sendgrid.py
- docs/esps/sendgrid.rst
- tests/test_sendgrid_inbound.py
- tests/utils.py
Fix a crash or text-mangling issue when an inbound message
uses a charset other than utf-8 for its text or html body,
and SendGrid's "post raw" inbound parse option is *not*
enabled.
Update docs to recommend "post raw" option.
Fixes #187
> SendGrid: fix inbound webhook Unicode error when not utf-8

- .travis.yml
- CHANGELOG.rst
- anymail/utils.py
- tests/test_inbound.py
Fix Anymail's backported get_content_disposition to handle
values containing non-ASCII filenames. (Only applies on
Python 2.7.)
Fixes #197
> Inbound: fix get_content_disposition with non-ASCII filename

- CHANGELOG.rst
- anymail/backends/mailjet.py
- docs/esps/mailjet.rst
- tests/test_mailjet_backend.py
- tests/test_mailjet_integration.py
[On hold awaiting Mailjet fix for v3.1 Send API regression in template From handling: Mailjet ticket # 830935 2018-01-22.]
Breaking change for `esp_extra` with Mailjet.
Switch from Mailjet's older v3.0 Send API to the latest v3.1 version.
The v3.1 API resolves some limitations/quirks of older API:
* Mailjet now correctly handles commas in recipient display names;
Anymail no longer works around this using MIME encoded-word syntax.
* Mailjet now supports mixing cc/bcc with merge_data; Anymail no longer
errors on this case.
* Mailjet now supports using a template's From email and name without
making an additional API call to retrieve them. (Not currently working
as documented; awaiting info from Mailjet before releasing.)
But v3.1 adds a new limitation:
* Mailjet supports only a single …
> Mailjet: Upgrade to Send API v3.1

- CHANGELOG.rst
- anymail/backends/sparkpost.py
- docs/esps/sparkpost.rst
- tests/test_sparkpost_backend.py
- tests/test_sparkpost_integration.py
SparkPost's API no longer allows this, and now returns
a confusing error message about return_path.
(Not treating as a breaking change in Anymail, because
the breaking change was in the SparkPost API. This just
improves the error message in the unlikely event anyone
is trying to use this feature.)
Closes #212
> SparkPost: drop support for multiple from_email

- tox.ini
Django has renamed their dev branch to "main".
(Also clean up some version reporting.)
> Update tox for Django dev branch install

- CHANGELOG.rst
- anymail/webhooks/amazon_ses.py
- tests/test_amazon_ses_webhooks.py
Allow inbound and tracking webhooks using SNS topics from any AWS region.
The topic subscription must be confirmed in the topic's own region (not
the boto3 default), determined by examing the topic's ARN.
Fixes #235
> Amazon SES: confirm webhook subscriptions in SNS topic's own region

- CHANGELOG.rst
- anymail/backends/postmark.py
- tests/test_postmark_backend.py
Postmark uses their ErrorCode 300 to report several different
send-time validation errors, some of which identify invalid
recipients that need to be handled specially, but many of which
are ordinary API errors.
Rework the logic for parsing ErrorCode 300 error messages:
Handle only "Invalid 'To'" or "Error parsing 'To'" (or 'Cc'
or 'Bcc') as recipient errors. Otherwise raise an API error.
Fixes #238 silent failure when sending with long metadata keys.
> Postmark: fix silent failures for send-time validation errors

- docs/requirements.txt
(And shush Dependabot about Pygments vulnerabilities
in lexers we don't use.)
> Docs: upgrade docs build tooling

- .github/workflows/ci-cd.yml
- README.rst
Update GitHub workflow to automatically release
when tagged with v* (following successful tests).
When a tag starting with v is pushed or created via
GH releases page, builds and publishes the package
to PyPI, creates or updates the GH release notes, and
uploads the package assets to the GH release artifacts.
Release will fail before publishing if the package version
doesn't match the git tag.
Workflow will not attempt release if tests don't pass.
If test failure is due to a transient error (e.g., ESP glitch),
restarting the workflow manually should publish the
release once the tests succeed.
Also upgrades workflow infrastructure to use:
* ubuntu-20.04 runner
* Python 3.9 for tox host
* fkirc/skip-duplicate-actions@3.4.0
> Automate release process

- CHANGELOG.rst
- anymail/backends/base.py
- anymail/backends/test.py
- tests/test_general_backend.py
Improve handling of alternative parts and `content_subtype`
to match how Django's SMTP backend handles some unusual cases.
Change Test backend to support (and record) text/* alternative
parts. (But still reject other types of alternatives.)
Fixes #252
> Treat first text/plain alternative as plaintext body

- CHANGELOG.rst
- anymail/exceptions.py
- tests/test_general_backend.py
Remove `AnymailError.describe_send`, which added sender and
recipient email addresses to every AnymailError message
(whether or not relevant to the error).
Addresses #245
> Fix: don't include sender/recipient in AnymailError description

- CHANGELOG.rst
- anymail/backends/test.py
- docs/tips/test_backend.rst
- tests/test_general_backend.py
Make it easier for tests to check whether messages
would fall under Anymail's batch-send logic.
See #249.
> Test backend: Add `is_batch_send` to `anymail_test_params`

- .github/workflows/test.yml
- tox.ini
Stop maintaining duplicate (and often not-quite-
in-sync) test matrices in tox.ini and test.yml.
> CI: get GitHub test matrix from tox envlist

- .github/workflows/test.yml
pypy-3.8-v7.3.8 accidentally shipped with sqlite v3.7.17, which is a decade old, and causes the tests to fail with `django.core.exceptions.ImproperlyConfigured: SQLite 3.9.0 or later is required`.
Until pypy-3.8-v7.3.9 is available in actions/setup-python, work around the problem by forcing unqualified "pypy-3.8" to specific (older) version "pypy-3.8-v7.3.7".
See https://foss.heptapod.net/pypy/pypy/-/issues/3690 and https://github.com/actions/setup-python/issues/339.
> Work around outdated pypy-3.8-v7.3.8 sqlite

- CHANGELOG.rst
- anymail/inbound.py
- anymail/webhooks/mailgun.py
- anymail/webhooks/sendgrid.py
- docs/esps/mailgun.rst
- docs/esps/sendgrid.rst
- tests/test_mailgun_inbound.py
- tests/test_sendgrid_inbound.py
- tests/utils.py
Workaround for Django multipart/form-data limitation
where certain attachment filenames cause fields to be dropped
or to end up in request.POST rather than request.FILES.
Handle the MultiValueDictKeyError in inbound webhooks when
this has occurred. Also update docs to recommend avoiding
the problem by using Mailgun and SendGrid's "raw MIME" options.
Also handle reported cases of empty, duplicate keys in Mailgun's
content-id-map.
Fixes #272
> Mailgun/SendGrid inbound: workaround Django filename issue

- CHANGELOG.rst
- anymail/webhooks/postmark.py
- tests/test_postmark_webhooks.py
Handle SubscriptionChange event in Postmark webhook.
This event was previously not handled and treated as event type Unknown.
The SuppressSending field indicates whether the SubscriptionChange was a deactivation or reactivation.
Postmark doesn't provide a consistent way to distinguish between explicit unsubscribes and bounces so a lot of bounced emails have event type sent to Unknown. This fix will prevent that and classify bounced, unsubscribed, and resubscribed emails correctly.
https://postmarkapp.com/developer/webhooks/subscription-change-webhook
> Fix: Handle SubscriptionChange event in Postmark webhook

- CHANGELOG.rst
- anymail/backends/base_requests.py
- docs/conf.py
- docs/tips/transient_errors.rst
The requests library lets you mount adapters to configure policy such as timeouts and retries. Here's an attempt at an API that extends anymail to let you do so. This is the initial draft, I am looking forward to feedback on how this should be done. I also skipped writing docs.
The functionality is exposed through a new ANYMAIL_REQUESTS_ADAPTERS configuration value in the Django settings:
```
ANYMAIL_REQUESTS_ADAPTERS = [
["https://foobar.com", HTTPAdapter(pool_connections=100)],
]
```
> Support requests session customization, document use for automatic retries

- CHANGELOG.rst
- anymail/backends/base.py
- anymail/utils.py
- anymail/webhooks/mailgun.py
- anymail/webhooks/mailjet.py
- anymail/webhooks/mandrill.py
- anymail/webhooks/postal.py
- anymail/webhooks/sendgrid.py
- anymail/webhooks/sendinblue.py
- anymail/webhooks/sparkpost.py
- docs/sending/anymail_additions.rst
- setup.py
- tests/test_amazon_ses_inbound.py
- tests/test_amazon_ses_webhooks.py
- tests/test_general_backend.py
- tests/test_mailgun_inbound.py
- tests/test_mailgun_webhooks.py
- tests/test_mailjet_webhooks.py
- tests/test_mandrill_webhooks.py
- tests/test_postal_webhooks.py
- tests/test_postmark_webhooks.py
- tests/test_sendgrid_webhooks.py
- tests/test_sendinblue_webhooks.py
- tests/test_sparkpost_backend.py
- tests/test_sparkpost_webhooks.py
- tox.ini
Handles the deprecation of django.utils.timezone.utc
~~This required aliasing utc dynamically based on the version of
Django in the utils module.~~
> Confirm support for Django 4.1.

- CHANGELOG.rst
- anymail/backends/sendinblue.py
- tests/test_sendinblue_backend.py
Work around recent (unannounced) Sendinblue API change that caused "Invalid headers" API error with non-string custom header values, by converting basic numeric types to strings. (Borrowed code from SendGrid backend.)
Fixes #288
> Sendinblue: fix "invalid headers" error

- docs/esps/mailjet.rst
The old link returns a 404 now
> Fix link to mailjet apikeys

- CHANGELOG.rst
- anymail/backends/sendinblue.py
- docs/esps/index.rst
- docs/esps/sendinblue.rst
- tests/test_sendinblue_backend.py
- tests/test_sendinblue_integration.py
Add support for delayed sending via
Sendinblue's public beta "scheduledAt"
parameter.
Closes #280
> Sendinblue: Support send_at

- CHANGELOG.rst
- setup.py
- tox.ini
Django 4.2 has been released. (Tests no longer need to ask for prerelease version.)
> Test release version of Django 4.2

- CHANGELOG.rst
- anymail/webhooks/postmark.py
- tests/test_postmark_inbound.py
Recently we discussed the issue that Postmark's inbound test webhooks are not in the same format as real inbound webhooks. 
I have created a workaround for this issue. Now anymail will handle the events without crashing. 
Also it will raise a warning, so that the user might consider testing with a real event before going to production.
I did my best to make this change according to the quality standards of this project. If something is missing or changed let me know. 
Closes #304
> Workaround for postmark inbound test email can not be parsed

- .github/workflows/test.yml
- CHANGELOG.rst
- setup.py
tox dependency virtualenv dropped support for creating Python 3.6 environments in a minor release. [1]
Announce deprecation of Anymail Python 3.6 support. Until that can take effect, pin an older version of virtualenv that still works for tox py36 testenv.
[1]: See https://github.com/pypa/virtualenv/pull/2548#issuecomment-1527278210 et seq
> Tests: get tox py36 tests working again

- CHANGELOG.rst
- anymail/inbound.py
- anymail/message.py
- tests/test_inbound.py
Fix `AnymailInboundMessage.to`, `.cc`, `.from_email` when message was built with `AnymailInboundMessage.construct()` using empty strings for those params. (Postmark inbound relies on this.)
Fixes #307
> Fix empty strings in AnymailInboundMessage from/to/cc

- CHANGELOG.rst
- anymail/backends/amazon_ses.py
- anymail/backends/amazon_sesv2.py
- anymail/backends/base_requests.py
- tests/test_amazon_ses_backend.py
- tests/test_amazon_sesv2_backend.py
- tests/test_base_backends.py
Make sure backends actually fail silently when asked (rather than raising inaccurate errors suggesting coding problems).
Fixes #308
> Fix fail_silently when session/client creation fails

- CHANGELOG.rst
- anymail/inbound.py
- anymail/webhooks/postmark.py
- docs/esps/postmark.rst
- tests/test_files/postmark-inbound-test-payload-with-raw.json
- tests/test_files/postmark-inbound-test-payload.json
- tests/test_inbound.py
- tests/test_postmark_inbound.py
- Support Postmark's RawEmail option; recommend it in docs
- Handle Bcc when provided by Postmark
- Obtain `envelope_sender` from Return-Path info Postmark now adds, rather than parsing Received-SPF
> Postmark inbound: improve inbound parsing

- CHANGELOG.rst
- README.rst
- anymail/backends/sendinblue.py
- docs/esps/brevo.rst
- docs/esps/index.rst
- docs/esps/sendinblue.rst
- pyproject.toml
- tests/test_sendinblue_backend.py
- tests/test_sendinblue_integration.py
Sendinblue change its name to Brevo (https://www.brevo.com/blog/becoming-brevo/).
The API is also available on the new domain. The previous one still works, so there is no emergency to patch and release.
This is a minimal change to update but I guess it would be better:
- to have a new backend `brevo.EmailBackend` with the implementation.
- `sendinblue.EmailBackend` would inherit `brevo.EmailBackend` to use the same URL but adding such warning:
```python3
warnings.warn("Sendinblue has renamed itself Brevo. Change to Brevo backend.", DeprecationWarning)
```
What do you think about it?
> Update domain to brevo.com

- CHANGELOG.rst
- anymail/backends/sendgrid.py
- docs/esps/sendgrid.rst
- tests/test_sendgrid_backend.py
- tests/test_sendgrid_integration.py
> SendGrid: support multiple reply_to

- CHANGELOG.rst
- docs/esps/mailgun.rst
Explain account-level "Mailgun API keys" vs. domain-level "sending API keys."
Resolves #335
> Mailgun (docs): Clarify API keys

- docs/_readme/template.txt
- docs/conf.py
- docs/requirements.txt
ReadTheDocs builds have started failing.
Updating to latest sphinx-rtd-theme and Sphinx seems to solve the problem.
(Also update other docs dependencies.)
> Docs: fix RTD Sphinx build, update deps

- CHANGELOG.rst
- anymail/backends/base.py
- anymail/utils.py
- anymail/webhooks/mailgun.py
- tests/test_general_backend.py
- tests/test_utils.py
Fixes merging global `SEND_DEFAULTS`
with message `esp_extra` for ESP APIs
that use nested payload structures.
And clarifies intent for other properties.
Fixes #338
> Fix global SEND_DEFAULTS merging

- docs/_static/table-formatting.js
- docs/conf.py
- docs/esps/esp-feature-matrix.csv
- docs/esps/index.rst
- pyproject.toml
Move the big ESP feature matrix table into a CSV file for easier maintenance.
Remove the doc8 line-length exception the old table needed.
Docutils csv-table directive doesn't support colspan on the subheadings like the old table did. Add some JS that replicates the old behavior. (The new table is still readable even with JS disabled.)
> Docs: simplify editing ESP feature matrix

- CHANGELOG.rst
- anymail/backends/resend.py
- docs/esps/esp-feature-matrix.csv
- docs/esps/resend.rst
- tests/test_resend_backend.py
- tests/test_resend_integration.py
Add support for `merge_metadata` and new Resend email/batch API.
Closes #356
> Resend: support batch send

- docs/_static/anymail-theme.css
- docs/requirements.txt
Upgrade to sphinx-rtd-theme 2.0.x
to fix broken links in search results
(for searches rendered client side).
See https://github.com/sphinx-doc/sphinx/issues/11608#issuecomment-1684410476 and https://github.com/readthedocs/sphinx_rtd_theme/pull/1507
> Docs: fix broken links in search results

- CHANGELOG.rst
- anymail/webhooks/mailgun.py
- tests/test_mailgun_webhooks.py
This fixes the case of delivery-status being None in the event data posted to mailgun webhook handler.
See: #361
> Fixed #361: AttributeError in mailgun webhooks

- .github/workflows/integration-test.yml
- CHANGELOG.rst
- anymail/backends/brevo.py
- anymail/backends/sendinblue.py
- anymail/urls.py
- anymail/webhooks/brevo.py
- anymail/webhooks/sendinblue.py
- docs/esps/brevo.rst
- pyproject.toml
- tests/test_brevo_backend.py
- tests/test_brevo_inbound.py
- tests/test_brevo_integration.py
- tests/test_brevo_webhooks.py
- tests/test_sendinblue_deprecations.py
- tox.ini
I've been rethinking my arguments in #321 about leaving "SendinBlue" in the code while calling it "Brevo" everywhere else. I now feel this creates more confusion (particularly with new users) than it avoids.
This PR renames "sendinblue" to "brevo" throughout the code, but maintains compatibility versions on the old names and URLs (with deprecation warnings). 
The compatibility versions use the old `esp_name`, which means that settings names and other related features are also unchanged. So if you have `EMAIL_BACKEND = "…⁠sendinblue.EmailBackend"`, Anymail will continue to look for `SENDINBLUE_API_KEY` in the settings. But when you update to `EMAIL_BACKEND = "…⁠brevo.EmailBackend"`, you'll need to switch to `BREVO_API_KEY` at the same time.
I don't have any particular schedule for removing …
> Brevo: Rename SendinBlue to Brevo

- docs/inbound.rst
It's `get_all`, not `getall`.  https://docs.python.org/3.12/library/email.message.html#email.message.EmailMessage.get_all
I checked python versions 3.6-3.12 and confirmed it's always been the case.
> Fix reference to non-existent method on `EmailMessage`

- CHANGELOG.rst
- anymail/backends/amazon_ses.py
- anymail/backends/base.py
- anymail/backends/test.py
- anymail/message.py
- tests/test_amazon_ses_backend.py
Please check  ReplacementHeaders
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendBulkEmail.html
This headers are very useful for the new requirements of email clients like gmail, yahoo, etc. 
Allows to add headers as a template. This enables, for example, to add an unique unique unsubscribe header for each email.
> Support merge_headers in Amazon SES bulk send

- docs/esps/sendgrid.rst
Thanks for this package!
Some of the SendGrid links are now not available anymore (404 error). Looks like they migrated the docs over to Twilio now. This PR fixes them.
> Fix broken sendgrid documentation links

- CHANGELOG.rst
- anymail/backends/amazon_ses.py
- docs/esps/amazon_ses.rst
- pyproject.toml
- tests/test_amazon_ses_backend.py
- tests/test_amazon_ses_integration.py
> Amazon SES: use ReplacementHeaders to relax restrictions on template send

- CHANGELOG.rst
- anymail/webhooks/sendgrid.py
- tests/test_sendgrid_webhooks.py
According https://www.twilio.com/docs/sendgrid/for-developers/tracking-events/event#dropped the correct "reason" value for bouncing addresses is "Bounced Address" and that seems to be what I am seeing in SendGrid logs. Without this change those events were being normalized by anymail to `type=dropped, reject_reason=other` and not `reject_reason=bounced`.
I used sample event from their docs, and kept original mapping value since I'm not sure if that may actually show up in other situations.
> SendGrid: better handling of event="dropped", reason="Bounced Address" webhook events.

- CHANGELOG.rst
- anymail/backends/mailersend.py
- docs/esps/mailersend.rst
- tests/test_mailersend_backend.py
- tests/test_mailersend_integration.py
Add support for MailerSend's new(ish) "headers" field.
> MailerSend: support extra_headers

- CHANGELOG.rst
- anymail/backends/sparkpost.py
- docs/esps/sparkpost.rst
- tests/test_sparkpost_backend.py
- tests/test_sparkpost_integration.py
Raise an `AnymailUnsupportedFeature` error when trying to use a `template_id` along with other content payload fields that SparkPost silently ignores when template_id is present:
- attachments
- inline images
- extra headers
- cc recipients (uses extra headers)
- from_email
- reply_to
(It's unclear if these used to cause API errors, or if they were supported with templates at some point and then quietly dropped.)
> SparkPost: error on features incompatible with template_id

- CHANGELOG.rst
- anymail/backends/amazon_ses.py
- tests/test_amazon_ses_backend.py
> Amazon SES: fix header encoding issue

- CHANGELOG.rst
- anymail/webhooks/brevo.py
- docs/esps/brevo.rst
- tests/test_brevo_webhooks.py
rel #385 
As talked about in the related issue, I've updated the mappings. I also added tests and docs. 
Furthermore, I tried to make the code comment I missed ( "request" event) stand out more, by moving all the comments from inline to above their related entry. I hope this is OK.
Very much looking forward to your comments!
> Brevo webhook updates

- CHANGELOG.rst
- anymail/backends/resend.py
- docs/esps/esp-feature-matrix.csv
- docs/esps/resend.rst
- tests/test_resend_backend.py
- tests/test_resend_integration.py
> Resend: add support for send_at

- anymail/webhooks/amazon_ses.py
In Amazon SES webhook views (tracking and inbound):
- Close boto3 clients after use. (Not strictly required, but doesn't hurt. Amazon SES backend was already doing this.)
- Break out some webhook functionality to simplify subclassing. (E.g., to handle S3 object encryption through outside tooling, as AWS hasn't released a Python version of their S3 encryption client.)
> Amazon SES: add webhook extension points; close webhook boto3 clients

- CHANGELOG.rst
- anymail/backends/mailjet.py
- docs/esps/mailjet.rst
- tests/test_mailjet_backend.py
- tests/test_mailjet_integration.py
Mailjet requires all attachments/inlines have a non-empty Filename field. Substitute `"attachment"` for missing filenames.
Fixes #407.
> Mailjet: Prevent empty attachment filename

- CHANGELOG.rst
- anymail/backends/mailjet.py
- tests/test_mailjet_backend.py
> Mailjet: Don't try to parse non-JSON responses as JSON.

- CHANGELOG.rst
- anymail/backends/postmark.py
- tests/test_postmark_backend.py
> Postmark: Handle responses with missing ErrorCode and delayed delivery

- CHANGELOG.rst
- anymail/backends/resend.py
- anymail/backends/sendgrid.py
- docs/contributing.rst
- tests/test_resend_backend.py
- tests/test_sendgrid_backend.py
Remove Anymail workarounds for SendGrid and Resend API bugs that have since been fixed.
> Remove outdated workarounds

- CHANGELOG.rst
- anymail/backends/sendgrid.py
- tests/test_sendgrid_backend.py
SendGrid returns a cryptic "Bad Request" error (with no other details) when legacy substitutions values are anything other than string or null. (This only applies to substitutions, for legacy templates and on-the-fly merge fields.)
Convert numeric types to string (per Anymail's documented `merge_data` behavior), and raise an AnymailSerializationError for other unsupported substitutions values.
Fixes #420
> SendGrid: Handle non-string data in legacy substitutions

- .github/workflows/integration-test.yml
- CHANGELOG.rst
- README.rst
- anymail/backends/sendgrid.py
- anymail/checks.py
- anymail/exceptions.py
- anymail/webhooks/sendgrid.py
- docs/esps/esp-feature-matrix.csv
- docs/esps/index.rst
- docs/esps/sendgrid.rst
- tests/test_checks.py
- tests/test_sendgrid_backend.py
- tests/test_sendgrid_inbound.py
- tests/test_sendgrid_webhooks.py
* Update docs to indicate SendGrid is no longer regularly tested, so is officially unsupported
* Disable SendGrid live integration tests (which have been failing due to disabled testing account)
* Add warning messages in SendGrid EmailBackend, inbound and tracking webhooks, and Django system checks when Anymail SendGrid features are used
* Add "Anymail support status" line to ESP feature matrix in the docs
Closes #432
> SendGrid: change to "unsupported" status

- .github/workflows/integration-test.yml
- pyproject.toml
- tox.ini
- Fix accidental ESP duplication in pyproject.toml keywords
- Alphabetize ESP names in pyproject.toml, tox.ini
- Enable scaleway in integration-test.yml
> Scaleway: cleanup and enable integration tests
